### ISSUE TITLE
1.5M DiffusionDB Aesthetic and Artifact Ratings

### ISSUE THREAD

**Issue by db0** [poloclub/diffusiondb#16]
Hey there I'm the creator of the [AI Horde](https://aihorde.net) and for the past year we've using our community to help us rate the diffusiondb output for aesthetics and artifacts.

I have created [a daily export of the ratings in huggingface](https://huggingface.co/datasets/Haidra-Org/AI-Horde-Ratings) and by today we have achieved 1.5 M ratings in ~300K images from diffusiondb. This is because we require 5 ratings per image in the dataset to ensure a good average. 

We started this ratings gathering [as a collaboration with LAION](https://dbzer0.com/blog/a-collaboration-begins-between-stable-horde-and-laion/) but they haven't been able to find anyone to process this data. I am bringing this to your attention in case you or the poloclub would be interested in crunching this dataset in any form.

**Comment by xiaohk** [comment]
Sorry for the late reply. Thank you so much for using DiffusionDB. AI Horde looks super interesting!
