### ISSUE TITLE
Bug in download.py

### ISSUE THREAD

**Issue by outrun32** [poloclub/diffusiondb#19]
`download.py` script has a few bugs: whenever I would run `python download.py -i 1`, it would automatically set `range_max = 2000` due to default value in `parser.add_argument` and it would always try to download the entire dataset. Besides that, the confirmation letter would never appear due to the condition `range_max - index > 1999` always being false. I have opened the PR to address this issues.

**Comment by xiaohk** [comment]
Good catch, thanks!
