### ISSUE TITLE
How to Create Fig. 6

### ISSUE THREAD

**Issue by WangWenhao0716** [poloclub/diffusiondb#22]
Many thanks for this excellent work. In the Page 6 and Fig. 6 of your paper, you show
```
https://poloclub. github.io/diffusiondb/explorer/#prompt-embedding
```
which is a very good visualization. However, I cannot find the code to generate this. Could you show me where it is?

**Comment by xiaohk** [comment]
Thanks for your kind words! The visualization has become WizMap, a standalone tool that enables users to visualize over 1M multimodal embedding points. You can learn more about WizMap here: https://github.com/poloclub/wizmap.

A demo with DiffusionDB is at: https://poloclub.github.io/wizmap/?dataset=diffusiondb

<video width="100%" src='https://github.com/poloclub/wizmap/assets/15007159/26d26336-e611-4d00-b535-8837da59be82'></video>

For the particular visualization used in DiffusionDB paper, the code is at https://github.com/poloclub/diffusiondb/tree/main/explorer.

**Comment by WangWenhao0716** [comment]
Many thanks for the reply and your great work

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by YSHMAN225** [comment]
I m sorry ,I m really interested in one of your project,may i have wechat or telegram with u.  
really thanks.

**Comment by WangWenhao0716** [comment]
yeah let talk on Wechat 18602459215

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
