### ISSUE TITLE
Stable diffusion version ? 

### ISSUE THREAD

**Issue by bertinma** [poloclub/diffusiondb#24]
Hi, 
Thank you for your amazing work :) 

I would like to know which version of Stable Diffusion is used to generate those images. Are there differentversions or only one ? 

Thanks for your help ;) 
Regards, 

Marc-Antoine

**Comment by xiaohk** [comment]
Thank you so much for your kind words!

All the images in DiffusionDB were scraped from Stable Diffusion Discord's bot channels, where users could request a bot account to generate images. These channels were only active from August 6th to 20th 2022. The model output displayed `stable-diffusion-v1` as the model label. I'm not sure if it is the same as the version `stable-diffusion-v1.1` on HuggingFace. All images are from the same version.

Hope this helps!

**Comment by bertinma** [comment]
Thanks for your quick answer, it helps a lot ;)
