### ISSUE TITLE
Licensing Question

### ISSUE THREAD

**Issue by fakerybakery** [poloclub/diffusiondb#25]
Hi,
Thanks for releasing this dataset! If the dataset contains prompts from the SD Discord server, are there any restrictions on their usage? I noticed that the dataset was CC0-licensed, but do any additional restrictions apply?
Thanks!

**Comment by xiaohk** [comment]
Hi! All the content in the SD discord server, such as prompts and images, are licensed as CC-1.0 based on the [SD Discord's Terms of Use](https://stability.ai/discord-tos). DiffusionDB is also released as CC-1.0, and there is no any additional restrictions.

**Comment by fakerybakery** [comment]
Makes sense, thank you!
