### ISSUE TITLE
Bug in download.py

### ISSUE THREAD

**Issue by zzl-pointcloud** [poloclub/diffusiondb#5]
script: python3 download.py -i 1 -r 2000
problem: there is only part-000001.zip left. All files are named as part-000001.zip.

Line99 in download.py, loop_file_path = f"{output}part-{index:06}.zip", should be changed to loop_file_path = f"{output}part-{idx:06}.zip"?

**Comment by xiaohk** [comment]
Hi @zzl-pointcloud, good catch, thanks! Do you want to open a PR to fix it?

Also cc @TheLustriVA.

**Comment by TheLustriVA** [comment]
I literally hit this problem last night. Will be a day or two before I can PR so first in is the hero ☺️

**Comment by zzl-pointcloud** [comment]
> Hi @zzl-pointcloud, good catch, thanks! Do you want to open a PR to fix it?
> 
> Also cc @TheLustriVA.

Yes, I have created a new pull request; please check it~

**Comment by zzl-pointcloud** [comment]
> I literally hit this problem last night. Will be a day or two before I can PR so first in is the hero ☺️

:smile:

**Comment by xiaohk** [comment]
#6 fixed this. Thanks!
